/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SendThankYouRouteImport } from './routes/send-thank-you'
import { Route as IndexRouteImport } from './routes/index'

const SendThankYouRoute = SendThankYouRouteImport.update({
  id: '/send-thank-you',
  path: '/send-thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/send-thank-you': typeof SendThankYouRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/send-thank-you': typeof SendThankYouRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/send-thank-you': typeof SendThankYouRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/send-thank-you'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/send-thank-you'
  id: '__root__' | '/' | '/send-thank-you'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SendThankYouRoute: typeof SendThankYouRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/send-thank-you': {
      id: '/send-thank-you'
      path: '/send-thank-you'
      fullPath: '/send-thank-you'
      preLoaderRoute: typeof SendThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SendThankYouRoute: SendThankYouRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
